name: CI TasksApi

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    # Setup do job
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    # ./Setup do job 
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: yarn find-deadcode
    - run: yarn lint-staged
